language: c
os: osx
osx_image: xcode10
compiler: clang
sudo: false
script:
    - make test

after_success:
    - bash <(curl -s https://codecov.io/bash)

addons:
    homebrew:
        packages:
            - check

branches:
    only:
        - master
        - develop
